name: job_postings

profile: job_postings

seed-paths: ["seeds"] 
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

flags:
  static_analysis: strict

models:
  job_postings:
    staging:
      +materialized: view

vars:
  retrieval_cap: 200