name: job_postings

profile: job_postings

seed-paths: ["seeds"] 
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  job_postings:
    staging:
      +materialized: view

seeds:
  job_postings:
    country_codes:
      +column_types:
        is_eu_member: boolean
        pay_transparency_effective_date: date
        requires_pay_in_job_ad: boolean
        legislation_checked_on: date
